variables:
  ADDITIONAL_TARGET_OPTIONS: "--exclude angular"

include:
  - component: gitlab.com/rxap/gitlab-ci/base@~latest
  - component: gitlab.com/rxap/gitlab-ci/nx-workspace@6.2.0-edge.12
    inputs:
      dte: true
      parallel: 5
