version: "3.7"
networks:
  default:
    name: traefik
services:
  traefik:
    image: traefik:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock:ro
      - ./docker/traefik:/etc/traefik:ro
    ports:
      - ${ROOT_DOMAIN_PORT}:443
      - 8888:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.rule=Host(`traefik.${ROOT_DOMAIN}`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    environment:
      - REMOTE_DOMAIN
      - ROOT_DOMAIN
      - ROOT_DOMAIN_PORT
      - HOST_IP
  catch-all-api:
    image: registry.gitlab.com/rxap/docker/catch-all:alpine
  rxap-service-configuration:
    image: registry.gitlab.com/rxap/packages/service/configuration:${RXAP_CHANNEL:-development}
    labels:
      - traefik.enable=true
      - traefik.http.services.rxap-service-configuration.loadbalancer.healthCheck.path=/health
      - traefik.http.services.rxap-service-configuration.loadbalancer.healthCheck.interval=10s
      - traefik.http.services.rxap-service-configuration.loadbalancer.healthCheck.timeout=3s
    volumes:
      - ./shared/service/configuration:/app/assets
    environment:
      - STATUS_SERVICE_BASE_URL=http://rxap-service-status:3000
      - ROOT_DOMAIN
      - SENTRY_ENABLED=false
      - LOG_LEVEL=verbose
      - ROOT_DOMAIN_PORT
      - ENVIRONMENT_NAME=development
    depends_on:
      - traefik
      - rxap-service-status
    env_file:
      - .env
  rxap-service-status:
    image: registry.gitlab.com/rxap/packages/service/status:${RXAP_CHANNEL:-development}
    labels:
      - traefik.enable=true
      - traefik.http.services.rxap-service-status.loadbalancer.healthCheck.path=/health
      - traefik.http.services.rxap-service-status.loadbalancer.healthCheck.interval=10s
      - traefik.http.services.rxap-service-status.loadbalancer.healthCheck.timeout=3s
    environment:
      - ROOT_DOMAIN
      - SENTRY_ENABLED=false
      - LOG_LEVEL=verbose
      - ROOT_DOMAIN_PORT
      - ENVIRONMENT_NAME=development
    depends_on:
      - traefik
    ports:
      - 5300:3000
    env_file:
      - .env
  rxap-service-changelog:
    image: registry.gitlab.com/rxap/packages/service/changelog:${RXAP_CHANNEL:-development}
    labels:
      - traefik.enable=true
      - traefik.http.services.rxap-service-changelog.loadbalancer.healthCheck.path=/health
      - traefik.http.services.rxap-service-changelog.loadbalancer.healthCheck.interval=10s
      - traefik.http.services.rxap-service-changelog.loadbalancer.healthCheck.timeout=3s
    environment:
      - STATUS_SERVICE_BASE_URL=http://rxap-service-status:3000
      - ROOT_DOMAIN
      - SENTRY_ENABLED=false
      - LOG_LEVEL=verbose
      - ROOT_DOMAIN_PORT
      - ENVIRONMENT_NAME=development
    volumes:
      - ./shared/service/changelog:/app/assets
    depends_on:
      - traefik
      - rxap-service-status
    env_file:
      - .env
  rxap-service-user:
    image: registry.gitlab.com/rxap/packages/service/user:${RXAP_CHANNEL:-development}
    labels:
      - traefik.enable=true
      - traefik.http.services.rxap-service-user.loadbalancer.healthCheck.path=/health
      - traefik.http.services.rxap-service-user.loadbalancer.healthCheck.interval=10s
      - traefik.http.services.rxap-service-user.loadbalancer.healthCheck.timeout=3s
    environment:
      - STATUS_SERVICE_BASE_URL=http://rxap-service-status:3000
      - ROOT_DOMAIN
      - SENTRY_ENABLED=false
      - LOG_LEVEL=verbose
      - ROOT_DOMAIN_PORT
      - ENVIRONMENT_NAME=development
    volumes:
      - ./shared/service/user:/app/assets
    depends_on:
      - traefik
      - rxap-service-status
    env_file:
      - .env
  cors-options:
    image: registry.gitlab.com/rxap/docker/cors-options:alpine
