export const SENTRY_MODULE_OPTIONS = Symbol('SentryModuleOptions');
export const SENTRY_INTERCEPTOR_OPTIONS = Symbol('SENTRY_INTERCEPTOR_OPTIONS');
export const CONSOLE_LOGGER_OPTIONS = Symbol('CONSOLE_LOGGER_OPTIONS');
