export const AUTH0_OPTIONS = Symbol('AUTH0_OPTIONS');
export const AUTH0_AUTHENTICATION_OPTIONS = Symbol('AUTH0_AUTHENTICATION_OPTIONS');
export const AUTH0_MANAGEMENT_OPTIONS = Symbol('AUTH0_MANAGEMENT_OPTIONS');
