service: demo
runtime: nodejs10

inbound_services:
- warmup

automatic_scaling:
  max_instances: 1
  min_instances: 0

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /(.+\..+)$
  static_files: \1
  upload: (.+\..+)
- url: /assets/(.*)
  static_files: assets/\1
  upload: assets/(.*)
- url: /fonts/(.*)
  static_files: fonts/\1
  upload: fonts/(.*)
- url: (.*)
  static_files: index.html
  upload: index.html
