.build:
  extends: .run-many
  stage: build
  tags:
    - e2-standard-2
  variables:
    TARGET: "build"
  environment:
    action: prepare
    name: $ENVIRONMENT_NAME
  artifacts:
    name: "${CI_COMMIT_REF_SLUG}_run-many_${TARGET}"
    paths:
      - dist
