.build:
  stage: build
  tags:
    - e2-standard-8
  extends: .run_all
  variables:
    TARGET: "build"
  environment:
    action: prepare
  artifacts:
    name: "${CI_COMMIT_REF_SLUG}_run-all_${TARGET}"
    paths:
      - dist
    reports:
      dotenv: deploy.env
