trigger:deploy:
  trigger:
    include:
      - local: .gitlab/ci/pipelines/deployment.yaml
  stage: .post
  allow_failure: true
  rules:
    # if release tag always deploy
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'
      when: on_success
    # if default branch always deploy
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    # if maintenance branch always deploy
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH =~ /^[0-9]+\.[0-9]+\.x|[0-9]+\.x$/'
      when: on_success
    # else only manual deploy
    - when: manual
