include:
  - local: .gitlab/ci/jobs/run.yaml
  - local: .gitlab/ci/jobs/docker.yaml
  - local: .gitlab/ci/jobs/startup.yaml
  - local: .gitlab/ci/jobs/deploy.yaml
  - local: .gitlab/ci/jobs/e2e.yaml
  - local: .gitlab/ci/jobs/component-test.yaml
  - local: .gitlab/ci/jobs/pages.yaml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - local: .gitlab/ci/jobs/qodana.yaml

stages:
  - test
  - run
  - docker
  - startup

variables:
  ENVIRONMENT_NAME: branch/$CI_COMMIT_REF_NAME
