include:
  - local: .gitlab/ci/jobs/run.yaml
  - local: .gitlab/ci/jobs/docker.yaml
  - local: .gitlab/ci/jobs/startup.yaml
  - local: .gitlab/ci/jobs/sentry.yaml
  - local: .gitlab/ci/jobs/deploy.yaml
  - local: .gitlab/ci/jobs/e2e.yaml
  - local: .gitlab/ci/jobs/component-test.yaml
  - local: .gitlab/ci/jobs/writerside.yaml

stages:
  - run
  - docker
  - startup
  - deploy

variables:
  ENVIRONMENT_NAME: release/$CI_COMMIT_TAG

run:
  variables:
    ADDITIONAL_TARGET_OPTIONS: "--channel $CI_ENVIRONMENT_SLUG"
