include:
  - local: .gitlab/ci/jobs/run.yaml
  - local: .gitlab/ci/jobs/docker.yaml
  - local: .gitlab/ci/jobs/sentry.yaml

stages:
  - run
  - docker
  - sentry

variables:
  ENVIRONMENT_NAME: release/$CI_COMMIT_TAG

run:
  variables:
    ADDITIONAL_TARGET_OPTIONS: "--channel $CI_ENVIRONMENT_SLUG"

sentry:
  extends: .sentry
