include:
  - local: .gitlab/ci/jobs/build.yaml
  - local: .gitlab/ci/jobs/docker.yaml

stages:
  - build
  - docker

variables:
  ENVIRONMENT_NAME: review/$CI_MERGE_REQUEST_IID

build:
  extends: .build
  environment:
    name: $ENVIRONMENT_NAME
