include:
  - local: .gitlab/ci/jobs/run.yaml
  - local: .gitlab/ci/jobs/docker.yaml
  - local: .gitlab/ci/jobs/startup.yaml
  - local: .gitlab/ci/jobs/component-test.yaml
  - template: Jobs/SAST.latest.gitlab-ci.yml
  - local: .gitlab/ci/jobs/pages.yaml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - local: .gitlab/ci/jobs/qodana.yaml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

stages:
  - test
  - run
  - docker
  - startup

variables:
  ENVIRONMENT_NAME: review/$CI_MERGE_REQUEST_IID
