include:
  - local: .gitlab/ci/jobs/build.yaml
  - local: .gitlab/ci/jobs/docker.yaml

stages:
  - build
  - docker

variables:
  ENVIRONMENT_NAME: review/$CI_MERGE_REQUEST_IID
  DEPLOYMENT_TIER: development

build:
  extends: .build
  environment:
    name: review/$CI_MERGE_REQUEST_IID
    deployment_tier: development
