include:
  - local: .gitlab/ci/jobs/run.yaml
  - local: .gitlab/ci/jobs/docker.yaml
  - local: .gitlab/ci/jobs/startup.yaml

stages:
  - run
  - docker
  - startup

variables:
  ENVIRONMENT_NAME: review/$CI_MERGE_REQUEST_IID
