export const CONSOLE_LOGGER_OPTIONS = Symbol('CONSOLE_LOGGER_OPTIONS');
export const RXAP_LOGGER_PRINT_MESSAGES = Symbol('RXAP_LOGGER_PRINT_MESSAGES');
export const RXAP_LOGGER_FORMAT_MESSAGE = Symbol('RXAP_LOGGER_FORMAT_MESSAGE');
